// All UI text (English by default). Localize by swapping this object.

export const strings = {
  title: 'POP HERO',
  holdToPlay: 'HOLD TO PLAY',
  paused: 'PAUSED',
  close: 'CLOSE!',
  perfect: 'PERFECT!',
  whew: 'WHEW!',
  newType: 'NEW!',
  tier: (t: number) => `TIER ${t}!`,
  hold: 'HOLD',
  yourTurn: (left: number) => `HOLD TO BLOW · ${left} LEFT`,
  unlocked: 'UNLOCKED!',
  selectAbility: 'SELECT A NEW ABILITY',
  pick: 'PICK',
  bossName: 'RAT KING',
  enraged: 'ENRAGED!',
  crit: 'CRIT!',
  frozen: 'FROZEN',
  locked: 'LOCKED!',
  fire: 'FIRE!',
  enemyTurn: 'ENEMY TURN',
  release: 'RELEASE!',
  avoid: 'AVOID',
  fillLock: 'FILL THE LOCK!',
  leftoverHp: (n: number) => `+${n} HP`,
  fullHp: 'FULL HP',
  waveClear: 'WAVE CLEAR',
  waveIntro: (n: number) => `WAVE ${n}`,
  wave: (n: number, total: number) => `WAVE ${n}/${total}`,
  boss: 'BOSS',
  stageClear: 'STAGE CLEAR',
  gameOver: 'DEFEATED',
  playAgain: 'PLAY AGAIN',
  copyStats: 'COPY STATS',
  copied: 'COPIED!',
  statWave: 'Wave reached',
  statTime: 'Time',
  statTurns: 'Turns',
  statBalloons: 'Balloons blown / collected',
  statPopped: 'Popped (spike / too full)',
  statAir: 'Avg. size at release',
  statBonus: 'CLOSE! / PERFECT!',
  statLocks: 'Locks opened / failed',
  statDamage: 'Damage taken',
  statCause: 'Defeated by',
  statNoUpgrades: 'No upgrades',
  resume: 'RESUME',
  restart: 'RESTART',
  sound: 'SOUND',
  music: 'MUSIC',
  haptics: 'HAPTICS',
  reducedMotion: 'REDUCED MOTION',
  on: 'ON',
  off: 'OFF',
};
