// All UI text (English by default). Localize by swapping this object.

export const strings = {
  title: 'POP HERO',
  holdToPlay: 'HOLD TO PLAY',
  paused: 'PAUSED',
  close: 'CLOSE!',
  perfect: 'PERFECT!',
  whew: 'WHEW!',
  newType: 'NEW!',
  powerNames: { fire: 'FIRE', ice: 'ICE', bomb: 'BOMB', heal: 'HEAL', star: 'STAR', redstar: 'RED STAR' } as Record<string, string>,
  tier: (t: number) => `TIER ${t}!`,
  hold: 'HOLD',
  yourTurn: (left: number) => (left < 0 ? 'HOLD TO BLOW' : `HOLD TO BLOW · ${left} LEFT`),
  unlocked: 'UNLOCKED!',
  selectAbility: 'SELECT A NEW ABILITY',
  pick: 'PICK',
  bossNames: { ratking: 'SLIME KING', mole: 'MAGMA KING' } as Record<string, string>,
  bossIncoming: 'BOSS INCOMING!!',
  elite: 'ELITE!',
  free: 'FREE',
  skip: 'SKIP',
  evolve: 'EVOLVE',
  stunned: 'STUNNED',
  knocked: 'KNOCKED!',
  execute: 'EXECUTE!',
  secondWind: 'SECOND WIND!',
  enraged: 'ENRAGED!',
  crit: 'CRIT!',
  frozen: 'FROZEN',
  locked: 'LOCKED!',
  fire: 'FIRE!',
  enemyTurn: 'ENEMY TURN',
  release: 'RELEASE!',
  avoid: 'AVOID',
  fillLock: 'FILL THE LOCK!',
  waveClear: 'WAVE CLEAR',
  waveIntro: (n: number) => `WAVE ${n}`,
  wave: (n: number, total: number) => `Wave ${n}/${total}`,
  boss: 'BOSS',
  stageClear: 'VICTORY',
  gameOver: 'DEFEAT',
  playAgain: 'PLAY AGAIN',
  continue: 'CONTINUE',
  rewards: 'REWARDS',
  home: 'HOME',
  start: 'START',
  battle: 'BATTLE',
  upgrades: 'UPGRADES',
  chapter: (n: number, name: string) => `${n}  ${name}`,
  newFeature: 'NEW FEATURE!',
  unlockedUpgrades: 'UPGRADES UNLOCKED',
  tapToContinue: 'tap to continue',
  rank: (n: number) => `APPRENTICE ${n}`,
  statNames: { damage: 'DAMAGE', health: 'HEALTH', armor: 'ARMOR' } as Record<string, string>,
  level: (n: number) => `LV.${n}`,
  rankUp: (coins: number) => `RANK UP! +${coins}`,
  best: (w: number) => `Best: wave ${w}`,
  copyStats: 'COPY STATS',
  copied: 'COPIED!',
  statWave: 'Wave reached',
  statTime: 'Time',
  statTurns: 'Turns',
  statBalloons: 'Balloons blown / collected',
  statPopped: 'Popped (spike / too full)',
  statAir: 'Avg. size at release',
  statBonus: 'CLOSE! / PERFECT!',
  statLocks: 'Locks opened / failed',
  statDamage: 'Damage taken',
  statCause: 'Defeated by',
  statNoUpgrades: 'No abilities',
  statStars: 'Stars / red stars',
  resume: 'RESUME',
  restart: 'RESTART',
  sound: 'SOUND',
  music: 'MUSIC',
  haptics: 'HAPTICS',
  reducedMotion: 'REDUCED MOTION',
  on: 'ON',
  off: 'OFF',
};
